// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://afjrtgpfwgfedjjqmqmj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFmanJ0Z3Bmd2dmZWRqanFtcW1qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwNzgxMjEsImV4cCI6MjA2NDY1NDEyMX0.Pfs_SAIqQkKf55a6TNptoKGOeOqg3RqmUsIOXeR45G8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);